name: Upload to CDN

on:
  push:
    branches:
      - 'main'

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - id: upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: team-researchops
          source: dist
          destination: '/'
          source_keep_parent_name: false
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # Provided as Organization Variable

      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
